#!/usr/bin/env node
/**
 * Generates blog post pages and the front-page feed from CMS markdown.
 *
 *   content/posts/<slug>.md  ->  blog/<slug>.html
 *                            ->  content/posts.json  (the whole feed, rebuilt)
 *
 * Run via `npm run build:blog`; Netlify runs it as part of the site build.
 *
 * The markdown filename is the slug, so a post's URL is stable as long as the
 * file keeps its name. Renaming a file changes the published URL.
 *
 * Posts with `externalUrl` get a feed entry that links off-site and no page of
 * their own -- that covers announcements that just point at a survey or signup.
 */

import { readFileSync, writeFileSync, readdirSync, mkdirSync, unlinkSync, existsSync } from 'node:fs';
import { join, basename } from 'node:path';
import matter from 'gray-matter';
import { marked } from 'marked';

const ROOT = new URL('..', import.meta.url).pathname;
const POSTS_DIR = join(ROOT, 'content/posts');
const BLOG_DIR = join(ROOT, 'blog');
const FEED_FILE = join(ROOT, 'content/posts.json');

/* Marks pages this script owns, so stale ones can be cleaned up without ever
   touching a hand-written page that happens to live in blog/. */
const GENERATED_MARKER = '<!-- Generated by tools/build-blog.mjs from content/posts/. Do not edit directly. -->';

const escapeHtml = (value) =>
  String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

/* The site opens off-site links in a new tab. Markdown gives plain anchors, so
   put those attributes back for http(s) targets -- relative links to our own
   pages and mailto: links stay as they are. */
marked.use({
  renderer: {
    link(href, title, text) {
      const url = String(href ?? '');
      const attrs = [`href="${escapeHtml(url)}"`];
      if (title) attrs.push(`title="${escapeHtml(title)}"`);
      if (/^https?:\/\//i.test(url)) attrs.push('target="_blank"', 'rel="noopener noreferrer"');
      return `<a ${attrs.join(' ')}>${text}</a>`;
    },
  },
});

/* Noon UTC keeps a plain YYYY-MM-DD from sliding to the previous day when the
   build machine is behind UTC. */
const formatDate = (iso) =>
  new Date(`${iso}T12:00:00Z`).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    timeZone: 'UTC',
  });

function renderPage(post, bodyHtml) {
  const indentedBody = bodyHtml
    .trim()
    .split('\n')
    .map((line) => (line.trim() ? `      ${line}` : ''))
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  ${GENERATED_MARKER}
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="${escapeHtml(post.description || post.excerpt)}" />
  <title>${escapeHtml(post.title)} – Seattle Emergency Hubs</title>
  <script>try{if(localStorage.getItem("seh-theme")==="dark")document.documentElement.setAttribute("data-theme","dark")}catch(e){}</script>
  <link rel="stylesheet" href="../css/style.css" />
</head>
<body>
  <a class="skip-link" href="#main-content">Skip to main content</a>
  <div id="site-header-placeholder"></div>

  <main id="main-content">
    <a href="../index.html" class="back-link">&larr; Back to Blog</a>

    <article class="post-article">
      <span class="post-tag">${escapeHtml(post.tag)}</span>
      <h1>${escapeHtml(post.title)}</h1>
      <p class="post-meta">${escapeHtml(formatDate(post.date))} &middot; ${escapeHtml(post.author)}</p>

${indentedBody}
    </article>
  </main>

  <div id="site-footer-placeholder"></div>

  <script src="../js/hubs.js"></script>
  <script src="../js/components.js"></script>
  <script src="../js/main.js"></script>
</body>
</html>
`;
}

function loadPosts() {
  if (!existsSync(POSTS_DIR)) {
    throw new Error(`No posts directory at ${POSTS_DIR}. Nothing to build.`);
  }

  const files = readdirSync(POSTS_DIR).filter((name) => name.endsWith('.md'));
  const posts = [];
  const problems = [];

  for (const file of files) {
    const slug = basename(file, '.md');
    const { data, content } = matter(readFileSync(join(POSTS_DIR, file), 'utf8'));

    if (data.draft) continue;

    for (const field of ['title', 'date', 'excerpt']) {
      if (!data[field]) problems.push(`${file}: missing required "${field}"`);
    }

    const date = data.date instanceof Date
      ? data.date.toISOString().slice(0, 10)
      : String(data.date ?? '').slice(0, 10);

    if (date && !/^\d{4}-\d{2}-\d{2}$/.test(date)) {
      problems.push(`${file}: date "${data.date}" is not YYYY-MM-DD`);
    }

    posts.push({
      slug,
      title: data.title,
      date,
      author: data.author || 'Seattle Emergency Hubs Team',
      tag: data.tag || 'News',
      image: data.image || '',
      imageAlt: data.imageAlt || '',
      imageLayout: data.imageLayout || 'standard',
      excerpt: data.excerpt,
      description: data.description || '',
      externalUrl: data.externalUrl || '',
      body: content,
    });
  }

  if (problems.length) {
    throw new Error(`Invalid post front matter:\n  - ${problems.join('\n  - ')}`);
  }

  posts.sort((a, b) => String(b.date).localeCompare(String(a.date)));
  return posts;
}

function main() {
  const posts = loadPosts();
  mkdirSync(BLOG_DIR, { recursive: true });

  const written = new Set();

  for (const post of posts) {
    if (post.externalUrl) continue; // Links off-site; no page to generate.

    const target = `${post.slug}.html`;
    writeFileSync(join(BLOG_DIR, target), renderPage(post, marked.parse(post.body)), 'utf8');
    written.add(target);
  }

  /* Drop pages we generated on an earlier run whose source markdown is gone. */
  let removed = 0;
  for (const name of readdirSync(BLOG_DIR).filter((n) => n.endsWith('.html'))) {
    if (written.has(name)) continue;
    const existing = readFileSync(join(BLOG_DIR, name), 'utf8');
    if (existing.includes(GENERATED_MARKER)) {
      unlinkSync(join(BLOG_DIR, name));
      removed += 1;
    }
  }

  const feed = {
    posts: posts.map((post) => {
      const entry = {
        title: post.title,
        url: post.externalUrl || `blog/${post.slug}.html`,
        date: post.date,
        author: post.author,
        tag: post.tag,
        excerpt: post.excerpt,
      };
      if (post.image) {
        entry.image = post.image;
        entry.imageAlt = post.imageAlt;
        entry.imageLayout = post.imageLayout;
      }
      return entry;
    }),
  };

  writeFileSync(FEED_FILE, `${JSON.stringify(feed, null, 2)}\n`, 'utf8');

  const external = posts.filter((p) => p.externalUrl).length;
  console.log(
    `build:blog -> ${written.size} page(s), ${external} external link post(s), ` +
      `${posts.length} feed entr${posts.length === 1 ? 'y' : 'ies'}` +
      (removed ? `, ${removed} stale page(s) removed` : '')
  );
}

main();
